### ISSUE TITLE
在服务器上无法登录

### ISSUE THREAD

**Issue by smilecat2788** [KasukuSakura/mirai-login-solver-sakura#11]
只要一登录就报错
是ubuntu的服务器但是我不会添加jvm参数
大佬能不能教一下
2022-12-05 14:22:51 E/console: java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(Unknown Source)
        at java.desktop/java.awt.Window.initGC(Unknown Source)
        at java.desktop/java.awt.Window.init(Unknown Source)
        at java.desktop/java.awt.Window.<init>(Unknown Source)
        at java.desktop/java.awt.Frame.<init>(Unknown Source)
        at java.desktop/java.awt.Frame.<init>(Unknown Source)
        at java.desktop/javax.swing.JFrame.<init>(Unknown Source)
        at mirai-login-solver-sakura-0.0.4.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.JFrameWithIco(SakuraLoginSolver.kt:312)
        at mirai-login-solver-sakura-0.0.4.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:85)
        at mirai-login-solver-sakura-0.0.4.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha(SakuraLoginSolver.kt:55)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:286)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Karlatemp** [comment]
为什么不用最新的呢

**Comment by Karlatemp** [comment]
防火墙

**Comment by smilecat2788** [comment]
好的谢谢，已经登录上了
