### ISSUE TITLE
扫描成功后无法登录

### ISSUE THREAD

**Issue by TopSpoofer** [KasukuSakura/mirai-login-solver-sakura#4]
/login qq my-password
2022-11-08 20:29:42 I/Bot.qq: Bot cancelled: Bot closed
Login failed: Error(bot=Bot(qq), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
2022-11-08 20:29:42 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(qq), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(qq), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: java.util.concurrent.CancellationException: Bot closed
		at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
		at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
		at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:84)
		at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
		at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
		... 4 more
	Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(qq), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)]

**Comment by Karlatemp** [comment]
solver只负责验证过程中数据的传递，相关问题的讨论在论坛也有
https://mirai.mamoe.net/topic/1653
