### ISSUE TITLE
命令行无法登录

### ISSUE THREAD

**Issue by Pinkuburu** [KasukuSakura/mirai-login-solver-sakura#5]
login myqq mypwd
Login failed: Error(bot=Bot(myqq), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
2022-11-15 15:41:30 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(myqq), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(myqq), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:309)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: java.awt.HeadlessException:
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
                at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(Unknown Source)
                at java.desktop/java.awt.Window.<init>(Unknown Source)
                at java.desktop/java.awt.Frame.<init>(Unknown Source)
                at java.desktop/java.awt.Frame.<init>(Unknown Source)
                at java.desktop/javax.swing.JFrame.<init>(Unknown Source)
                at mirai-login-solver-sakura-0.0.4.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.JFrameWithIco(SakuraLoginSolver.kt:312)
                at mirai-login-solver-sakura-0.0.4.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:85)
                at mirai-login-solver-sakura-0.0.4.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha(SakuraLoginSolver.kt:55)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:279)
                ... 10 more

2022-11-15 15:41:30 I/Bot.myqq: Bot cancelled: Bot closed

**Comment by Karlatemp** [comment]
1. #1
2. README已经告诉你了, cli还在做

![图片](https://user-images.githubusercontent.com/30070303/201886199-258b208a-203e-401f-bc79-c1dd0744dfcd.png)
